server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "Y9iUYehakzeuRKnXWdEmVFqiw0X537HTaV5vkmgUZi9svYqe9QEw3SCtzhnBHlWw"
  valid-duration: 10
  refreshable-duration: 20